# Generated by Django 4.0.2 on 2022-04-15 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_allform_todo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Allform',
        ),
    ]
